[package]
name = "ppm"
version = "0.1.0"
authors = ["Chaofu <chaofuhuang1996@gmail.com>", "Baptiste <baptiste.fvt@gmail.com>", "Aminata <keitaaminata444@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
